### ISSUE TITLE
breaks when sending html email with attachments

### ISSUE THREAD

**Issue by christopherdarling** [azt3k/abc-silverstripe-mailer#5]
Running SS3.2.1

always fails on get_file_contents() due to $attachedFiles already containing the files contents and not the file path.

**Comment by azt3k** [comment]
Yes this is a known issue - currently it only works with files that exist in the file system.

**Comment by christopherdarling** [comment]
Ahh right, couldn't see it documented anywhere but could well have missed
it... Maybe worth adding if it's not though?

On Tuesday, 8 December 2015, azt3k <notifications@github.com> wrote:

> Yes this is a known issue - currently it only works with files that exist
> in the file system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azt3k/abc-silverstripe-mailer/issues/5#issuecomment-162994024>
> .
>


-- 
Kind Regards,
Christopher Darling
www.christopherdarling.co.uk

**Comment by azt3k** [comment]
Definitely worth adding.

**Comment by azt3k** [comment]
attachFileFromString support was added in 0.5.0 - can you retest with that release

**Comment by azt3k** [comment]
Closing this issue  - if you have any other problems feel free to raise another issue
